ADMIN = 'ADMIN'
MOVIE_FILLER = 'MOVIE_FILLER'
COMMON_USER = 'COMMON_USER'

GROUP_CHOICES = (
    (ADMIN, 'ADMIN'),
    (MOVIE_FILLER, 'MOVIE_FILLER'),
    (COMMON_USER, 'COMMON_USER')
)

PENDING = 'PENDING'
ACCEPTED = 'ACCEPTED'
REJECTED = 'REJECTED'

APPLICATION_STATUS = (
    (PENDING, 'PENDING'),
    (ACCEPTED, 'ACCEPTED'),
    (REJECTED, 'REJECTED')
)