# Generated by Django 3.2.3 on 2021-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.JSONField(default='ACTION'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.JSONField(),
        ),
    ]
