MALE = 'MALE'
FEMALE = 'FEMALE'
OTHER = 'OTHER'

GENDER_CHOICES = (
    (MALE, 'MALE'),
    (FEMALE, 'FEMALE'),
    (OTHER, 'OTHER')
)

ADMIN = "ADMIN"


ACTION = "ACTION"
ADVENTURE = "ADVENTURE"
ART_HOUSE = "ART_HOUSE"
COMEDY = "COMEDY"
MYSTERY = "MYSTERY"
FANTASY = "FANTASY"
HISTORICAL = "HISTORICAL"
HORROR = "HORROR"
ROMANCE = "ROMANCE"
SATIRE = "SATIRE"
BLACK_COMEDY = "BLACK_COMEDY"
SCI_FI = "SCI_FI"
THRILLER = "THRILLER"
WESTERN = "WESTERN"
DOCUMENTARY = "DOCUMENTARY"
MUSICAL = "MUSICAL"
TV_SERIES = "TV_SERIES"
INDIE = "INDIE"

GENRE_CHOICES = (
    (ACTION, 'ACTION'),
    (ADVENTURE, 'ADVENTURE'),
    (ART_HOUSE, 'ART_HOUSE'),
    (COMEDY, 'COMEDY'),
    (MYSTERY, 'MYSTERY'),
    (FANTASY, 'FANTASY'),
    (HISTORICAL, 'HISTORICAL'),
    (HORROR, 'HORROR'),
    (ROMANCE, 'ROMANCE'),
    (SATIRE, 'SATIRE'),
    (BLACK_COMEDY, 'BLACK_COMEDY'),
    (SCI_FI, 'SCI_FI'),
    (THRILLER, 'THRILLER'),
    (WESTERN, 'WESTERN'),
    (DOCUMENTARY, 'DOCUMENTARY'),
    (MUSICAL, 'MUSICAL'),
    (TV_SERIES, 'TV_SERIES'),
    (INDIE, 'INDIE'),
)
