# Generated by Django 3.2.3 on 2021-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_genre',
            field=models.CharField(blank=True, choices=[('ADVENTURE', 'ADVENTURE'), ('COMEDY', 'COMEDY'), ('MYSTERY', 'MYSTERY'), ('FANTASY', 'FANTASY'), ('HISTORICAL', 'HISTORICAL'), ('HORROR', 'HORROR'), ('ROMANCE', 'ROMANCE'), ('SATIRE', 'SATIRE'), ('BLACK_COMEDY', 'BLACK_COMEDY'), ('SCI_FI', 'SCI_FI'), ('THRILLER', 'THRILLER'), ('WESTERN', 'WESTERN'), ('DOCUMENTARY', 'DOCUMENTARY'), ('MUSICAL', 'MUSICAL'), ('TV_SERIES', 'TV_SERIES'), ('INDIE', 'INDIE')], max_length=25, null=True),
        ),
    ]
