# Generated by Django 3.2.3 on 2021-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210530_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_genre',
            field=models.CharField(blank=True, choices=[('ACTION', 'ACTION'), ('ADVENTURE', 'ADVENTURE'), ('ART_HOUSE', 'ART_HOUSE'), ('COMEDY', 'COMEDY'), ('MYSTERY', 'MYSTERY'), ('FANTASY', 'FANTASY'), ('HISTORICAL', 'HISTORICAL'), ('HORROR', 'HORROR'), ('ROMANCE', 'ROMANCE'), ('SATIRE', 'SATIRE'), ('BLACK_COMEDY', 'BLACK_COMEDY'), ('SCI_FI', 'SCI_FI'), ('THRILLER', 'THRILLER'), ('WESTERN', 'WESTERN'), ('DOCUMENTARY', 'DOCUMENTARY'), ('MUSICAL', 'MUSICAL'), ('TV_SERIES', 'TV_SERIES'), ('INDIE', 'INDIE')], max_length=25, null=True),
        ),
    ]
